config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :posts do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  get '/', to: 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :comments
  belongs_to :user

  validates :title, presence: true, length: { in: 1...250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_post_counter

  private

  def update_post_counter
    user.update(post_counter: user.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :post_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params_provider)
    @comment.user = current_user
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      flash[:notice] = 'Comment created succesfully'
      redirect_to user_post_url(user_id: params[:user_id], id: params[:post_id])
    else
      flash[:alert] = 'Failed to create new comment!'
      render :new
    end
  end

  def params_provider
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.user = current_user
    @like.post = Post.find(params[:post_id])
    if @like.save
      flash[:notice] = 'Like created succesfully'
      redirect_to user_post_url(user_id: params[:user_id], id: params[post_id])
    else
      flash[:alert] = 'Failed to create like!'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params_provider)
    @post.user = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_posts_url(current_user)
    else
      flash[:alert] = 'Could not create post!'
      render :new
    end
  end

  def params_provider
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: user_post_comments_path do |form| %>

<div>
    <%= form.label :Comment %></br>
    <%= form.text_area :text, size: "70x5" %>
</div>

<div>
    <%= form.submit value="Comment" %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, url: user_posts_url, class: "form" do |form| %>
<div class="form-items">
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>
<div class="form-items">
    <%= form.label :text %>
    <%= form.text_field :text %>
</div>
<div class="btn-submit">
    <%= form.submit value="Post" %>
</div>

app/views/posts/index.html.erb
<div>
     <div class="user-info">
      <img src = <%= @user.photo %> alt="profile pic"/>
        <p> <%= @user.name %> </p>
        <p> Number of posts: <%= @user.posts.count %> </p>
    </div>
    <ul class="user-posts">
        <% @user.posts.each do |post| %>
            <a href = <%= user_post_url(id: post.id) %>>
                <li>
                <h3> <%= post.title %></h3>
                <p> <%= post.text %></p>
                <div class="post-info">
                    Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
                </div>
                <ul class = "post-comments">
                   <% post.comments.each do |comment| %> 
                   <li>
                        <%= comment.text %>
                   </li>
                   <% end %>
                </ul>
            </li>
            </a>
        <% end %>
    </ul>
      <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<%= render 'shared/form', post: @post %>

app/views/posts/show.html.erb
<div class = "post">
    <div class="post-info">
        <p>Post # <%= @post.id %> by <%= @user.name %> </p>
        <p> Comments: <%= @post.comments_counter%> Likes: <%= @post.likes_counter%> </p>
    </div>
    <div class="post-body">
        <%= @post.text%>
    </div>
    <ul class="post-comments">
       <% @post.comments.includes(:post).each do |comment| %>
        <li>
            <%= comment.text %>
        </li>
        <% end %>
    </ul>
</div>

app/views/shared/_form.html.erb
<%= form_with model: post, url: user_posts_url, class: "form" do |form| %>
<div class="form-items">
    <%= form.label :title %></br>
    <%= form.text_field :title %>
</div>
<div class="form-items">
    <%= form.label :text %></br>
    <%= form.text_area :text, size: "70x5" %>
</div>
<div class="btn-submit">
    <%= form.submit value="Post" %>
</div>
<% end %>

app/views/users/index.html.erb
<head>
    <%= javascript_include_tag 'user_index_script', defer: true%>
</head>
<ul>
  <% @users.each do |user| %>
    <li id = <%= user.id %> class = "user-card">
        <a href = <%= "#{users_url}/#{user.id}"%>>
            <img src = <%= user.photo %> alt="profile pic"/>
            <div class="user-info">
                <p> <%= user.name %> </p>
                <p> Number of posts: <%= user.posts.count %> </p>
            </div>
        </a>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="user-details">
    <img src = <%= @user.photo %> alt="profile pic"/>
    <div class="user-info">
        <p> <%= @user.name %> </p>
        <p> Number of posts: <%= @user.posts.count %> </p>
    </div>
    <div class="user-bio">
        <h3>Bio</h3>
        <p> <%= @user.bio %> </p>
    </div>
    <ul class="user-posts">
        <% @user.posts.each_with_index do |post, i| %>
            <% if i < 3 %>
                <li>
                    <a href="<%= "#{user_posts_url(@user.id)}/#{post.id}" %>">
                        <h3> <%= post.title %></h3>
                        <p> <%= post.text %></p>
                        <div class="post-info">
                            Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
                        </div>
                    </a>
                </li>
            <% end %>
        <% end %>
    </ul>
    <a href= <%= user_posts_path(user_id: @user.id) %>>
        <button id="btn-see-all-posts">See all posts</button>
    </a>
</div>